### ISSUE TITLE
Invalid output when indexing anonymous table

### ISSUE THREAD

**Issue by fnuecke** [mathiasbynens/luamin#15]
I'm not sure if there's a special term for this, but I'm talking about this pattern: `({...})[key]`.

For example: `luamin.minify("print(({})[1])")` will output
`print({}[1])` which is invalid. It should remain as `print(({})[1])`.

Tested with luaparse 0.1.4 and luamin 0.2.7.

**Comment by yihuang** [comment]
What's the status of the bug with anonymous function?

**Comment by EdanPyx** [comment]
Well I just took a look and decided to fix this. I think this project has probably been abandoned since the fix was so easy.

Just change this result = formatExpression(expression.base) + '('; to this

https://github.com/mathiasbynens/luamin/blob/master/luamin.js#L329

`                        if(expression.base.inParens && expression.base.type == 'FunctionDeclaration')
                                result = '(' + formatExpression(expression.base) + ')('
                        else
                                result = formatExpression(expression.base) + '(';
`

If you have any future issues you can easily debug them by running luaparse and looking at what the AST looks like

`./luaparse -b -c '(function()end)()'
{
  "type": "Chunk",
  "body": [
    {
      "type": "CallStatement",
      "expression": {
        "type": "CallExpression",
        "base": {
          "type": "FunctionDeclaration",
          "identifier": null,
          "isLocal": false,
          "parameters": [],
          "body": [],
          "inParens": true
        },
        "arguments": []
      }
    }
  ],
  "comments": []
}
`

**Comment by mathiasbynens** [comment]
@EdanPyx Care to submit a pull request?

**Comment by EdanPyx** [comment]
Yes I was just thinking about making it now.

**Comment by EdanPyx** [comment]
Done https://github.com/mathiasbynens/luamin/pull/36

**Comment by mathiasbynens** [comment]
575a4bbf295b53ab9bc0cc0f5974c5fce72976fb
